openapi: '3.0.2'
info:
  title: 'YukEvent'
  version: '1.0'
servers:
  - url: 'http://localhost:8080/'
paths:
  '/user':
    get:
      operationId: "ResponseUser"
      responses:
        '201':
          description: OK

